language: julia
julia:
  - 1.1
  - 1.3
  - nightly
  
os:
  - linux
  - osx
  - windows

notifications:
  email: xuecheng@nuaa.edu.cn


after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'


matrix:
  allow_failures:
    - julia: nightly